language: elixir
elixir:
  - '1.10'
otp_release:
  - '20.2.2'
dist: bionic
env: MIX_ENV=test NERVES_TARGET=host
install: mix local.rebar --force ; mix local.hex --force
script: ./scripts/run-tests.sh
