language: elixir
elixir:
  - '1.9.1'
otp_release:
  - '22.1.5'
dist: focal
env: MIX_ENV=test NERVES_TARGET=host
install: mix local.rebar --force ; mix local.hex --force
script: ./scripts/run-tests.sh
